# Generated by Django 4.1 on 2022-08-25 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('edu_id', models.AutoField(primary_key=True, serialize=False)),
                ('SSC', models.CharField(default='Secondary School Certificate', max_length=255)),
                ('School_Name', models.CharField(max_length=255)),
                ('SSC_Percentage', models.PositiveIntegerField()),
                ('SSC_Passing_Year', models.DateField(max_length=6)),
                ('HSC', models.CharField(default='Higher Secondary School Certificate', max_length=255)),
                ('College_Name', models.CharField(max_length=255)),
                ('HSC_Percentage', models.PositiveIntegerField()),
                ('HSC_Passing_Year', models.DateField(max_length=6)),
                ('University', models.CharField(default=' Graduation', max_length=255)),
                ('University_Name', models.CharField(max_length=255)),
                ('Graduation_Percentage', models.PositiveIntegerField()),
                ('Graduation_Passing_Year', models.DateField(max_length=6)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
