# Generated by Django 4.1 on 2022-08-25 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companay_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('currently_working', models.DateField(auto_now=True)),
                ('total_Experience', models.IntegerField()),
                ('current_CTC', models.IntegerField()),
                ('Notice_Period', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
