# Generated by Django 4.1 on 2022-08-25 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.CharField(choices=[('PYTHON', 'Backend'), ('JAVA', 'Backend'), ('HTML5', 'Frontend'), ('CSS3', 'Frontend'), ('JAVASCRIPT', 'Frontend'), ('ANGULAR', 'Framework'), ('DJANGO', 'Framework'), ('FLASK', 'Framework')], default='Choose Your Skills', max_length=15)),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
