# Generated by Django 4.1 on 2022-08-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skills',
            field=models.CharField(default='Enter Your Skills', max_length=15),
        ),
    ]
