# Generated by Django 4.1 on 2022-08-27 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_alter_skill_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='College_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='Graduation_Passing_Year',
            new_name='Passing_Year',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='HSC_Percentage',
            new_name='Percentage',
        ),
        migrations.RemoveField(
            model_name='education',
            name='Graduation_Percentage',
        ),
        migrations.RemoveField(
            model_name='education',
            name='HSC',
        ),
        migrations.RemoveField(
            model_name='education',
            name='HSC_Passing_Year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='SSC',
        ),
        migrations.RemoveField(
            model_name='education',
            name='SSC_Passing_Year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='SSC_Percentage',
        ),
        migrations.RemoveField(
            model_name='education',
            name='School_Name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='University',
        ),
        migrations.RemoveField(
            model_name='education',
            name='University_Name',
        ),
        migrations.AddField(
            model_name='education',
            name='Education',
            field=models.CharField(choices=[('Secondary School Certificate', 'SSC'), ('Higher Secondary School Certificate', 'HSC'), (' Graduation', 'Graduation')], default='Select your Choices', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
