# Generated by Django 4.1 on 2022-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_rename_image_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Education',
            field=models.CharField(choices=[('SSC', 'Secondary School Certificate'), ('HSC', 'Higher Secondary School Certificate'), ('Graduation', 'Graduation')], max_length=255),
        ),
    ]
