# Generated by Django 4.1 on 2022-08-27 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0016_alter_education_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Marital_Status', models.CharField(choices=[('Single', 'Single/Unmarried'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Seprated', 'Seprated'), ('Other', 'Other')], max_length=255)),
                ('category', models.CharField(choices=[('Genral', 'Genral'), ('SC', 'Scheduled Cast'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other backword'), ('Other', 'Other')], max_length=255)),
                ('Differently_Abled', models.BooleanField(default=False)),
                ('Work_Permit_for_USA', models.BooleanField(default=False)),
                ('Permanent_Address', models.CharField(max_length=255)),
                ('Hometown', models.CharField(max_length=255)),
                ('Pincode', models.PositiveIntegerField()),
                ('Language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Marathi', 'Marathi')], max_length=15)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
