# Generated by Django 4.1 on 2022-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0018_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='id',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(default=None, max_length=250, upload_to='resume/'),
            preserve_default=False,
        ),
    ]
