# Generated by Django 4.1 on 2022-08-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0019_remove_resume_id_resume_resume_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_id',
        ),
        migrations.AddField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
