# Generated by Django 4.1 on 2022-08-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0025_basicprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicprofile',
            old_name='b_CTC',
            new_name='CTC',
        ),
        migrations.RenameField(
            model_name='basicprofile',
            old_name='b_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='basicprofile',
            old_name='b_experiance',
            new_name='experiance',
        ),
        migrations.RenameField(
            model_name='basicprofile',
            old_name='b_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='basicprofile',
            old_name='b_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='basicprofile',
            old_name='b_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='basicprofile',
            name='b_notice_period',
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='about',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='notice_period',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
