# Generated by Django 4.1 on 2022-08-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0026_rename_b_ctc_basicprofile_ctc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skill',
        ),
    ]
