# Generated by Django 4.1 on 2022-08-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0029_alter_skill_skills_socialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicprofile',
            name='designation',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
