# Generated by Django 4.1 on 2022-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0031_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Country',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone_number',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
